### ISSUE TITLE
Incorrect Link: Broken URL 

### ISSUE THREAD

**Issue by yashpimple** [kubesimplify/kblogs#3]
Description: 
In the contributing.md guide of the `kblogs` repository, there is a broken link under the section of "`Guideline for Blog Posts`" The link mentioned in the "Style Guide" subsection is not functioning correctly, preventing contributors from accessing the relevant content.

Steps to Reproduce:

1. Go to the [contributing.md](https://github.com/kubesimplify/kblogs/blob/main/CONTRIBUTING.md) file in the kblogs repository.
2. Scroll down to the "Guideline for Blog Posts" section.
3. Locate the "Style Guide" subsection.
4. Click on the broken link mentioned in the subsection.

Expected Behavior:
When the link in the "[Style Guide](https://github.com/kubesimplify/kblogs/blob/main/STYLE_GUIDE.md)" subsection is clicked, it should direct users to the corresponding style guide document.

Actual Behavior:
The link provided in the "Style Guide" subsection is broken, leading to an error page or an inaccessible resource.

Additional Information:
Screenshot related to the broken link can be found [here](https://github.com/kubesimplify/kblogs/assets/97302447/502a8275-af47-4029-8eec-a3519da93e2b)

CC:
@verma-kunal

**Comment by verma-kunal** [comment]
Thanks for pointing this out @YashPimple ! Pushed the fix for this
Closing this issue now
