### ISSUE TITLE
ksctl in a nutshell

### ISSUE THREAD

**Issue by Horiodino** [kubesimplify/kblogs#4]
well i was thinking to write a blog on the working of ksctl 

the way i am going to explain the working is by-breaking everything into smaller topics  

firstly i will explain the whats the ksctl used for and what problem it can solve !...
then we will move forward to k3s  by explaining its components  as ksctl is majorly focused on ha , 
and also going to explain the ha and managed Kubernetes and at the last a detailed diagram 
of ksctl  .

that's it :) what you guys think

**Comment by karnatisrinivas** [comment]
I really liked the idea, and as ksctl project is growing, we need a blogpost explaining it.

I know it is too much to ask but can you also possibly explain a small demo on ksctl usage?

**Comment by Horiodino** [comment]
> I know it is too much to ask but can you also possibly explain a small demo on ksctl usage?

well OK but its going to take a little bit more time .. but i surely do

**Comment by dipankardas011** [comment]
> well i was thinking to write a blog on the working of ksctl
> 
> the way i am going to explain the working is by-breaking everything into smaller topics
> 
> firstly i will explain the whats the ksctl used for and what problem it can solve !... then we will move forward to k3s by explaining its components as ksctl is majorly focused on ha , and also going to explain the ha and managed Kubernetes and at the last a detailed diagram of ksctl .
> 
> that's it :) what you guys think

you didn't told me 😉

**Comment by Horiodino** [comment]
> 

sorry i posted in kblog-channel so everyone can  put there opinions ..

**Comment by dipankardas011** [comment]
@pavangudiwada or @verma-kunal anyone of you when reviewing this issue can you add me and avinesh as reviewers as well

**Comment by dipankardas011** [comment]
> well i was thinking to write a blog on the working of ksctl
> 
> the way i am going to explain the working is by-breaking everything into smaller topics
> 
> firstly i will explain the whats the ksctl used for and what problem it can solve !... then we will move forward to k3s by explaining its components as ksctl is majorly focused on ha , and also going to explain the ha and managed Kubernetes and at the last a detailed diagram of ksctl .
> 
> that's it :) what you guys think

one more thing you can avoid explaining the detail of how the project structure is made as it will change completely

**Comment by dipankardas011** [comment]
you can instead explain the workflow and what is used and why that should be pretty good

**Comment by verma-kunal** [comment]
> @pavangudiwada or @verma-kunal anyone of you when reviewing this issue can you add me and avinesh as reviewers as well

Sure! This would be open for a review to all, even the members of Kubesimplify! 
Anyone can review and leave their thoughts. Thats the main purpose of creating a repo for this 🙂

**Comment by verma-kunal** [comment]
Great idea @Horiodino ! You can surely go ahead and start working on the blog! 
Feel free to ask your question either on this issue or #kblogs channel on discord.

All the best 🌟

**Comment by Horiodino** [comment]
> Great idea @Horiodino ! You can surely go ahead and start working on the blog! Feel free to ask your question either on this issue or #kblogs channel on discord.
> 
> All the best star2

thank you i will start right now   ;)

**Comment by Horiodino** [comment]
i will take some time guys is it ok ?

**Comment by verma-kunal** [comment]
Closing this as the blog's already been published: https://blog.kubesimplify.com/ksctl-making-kubernetes-easy-across-clouds
