### ISSUE TITLE
Install Kubernetes on MacBook Pro (M series) using kubeadm

### ISSUE THREAD

**Issue by adityasamant25** [kubesimplify/kblogs#9]
Hi,
I would like to write a step by step tutorial on how to set up a 3 node Kubernetes cluster on a MacBook Pro laptop running on **Apple silicon chips (M series)**. VirtualBox does not have a GA release for M series laptops (only developer previews are present). As such I believe it is important that readers would use a **compatible virtualization solution** to provision their VMs.
My post uses [Canonical's multipass](https://multipass.run/).

My solution is resilient to laptop restarts and ensures that the VMs are allocated the same IP addresses even after restarts, which is very important for the Kubernetes cluster to function in the long run.

This will be great for readers who would like to setup and manage their own Kubernetes cluster locally, without relying only on minikube, kind, K3s or MicroK8s.

Awaiting your feedback if this blog post would be beneficial for KubeSimplify.

**Comment by verma-kunal** [comment]
Hey @adityasamant25 , thank you so much for the proposal. This definitely sounds interesting & will certainly help a lot of folks out there.

Two questions:
- when can we expect a rough TOC?
- tentative date for the 1st draft?

Looking forward to this & please don't hesitate to ask for any help, if needed throughout the process!

**Comment by adityasamant25** [comment]
@verma-kunal Thanks for accepting my proposal.

> when can we expect a rough TOC?

By TOC, I assume you mean table of contents?
The table of contents would be:
- Introduction
- Prerequisites
- Provisioning the VMs (controlplane and worker nodes)
- Configuring local DNS
- Installing Kubernetes
* Install prerequisites for kubeadm
* Installing the container runtime
* Installing kubeadm, kubelet and kubectl
* Configuring crictl to work with containerd
* Initializing the controlplane node
* Installing a Pod network addon
* Join the worker nodes to the cluster
* Validation
- Capturing a backup (snapshot) of your cluster for easy recovery
- Cleanup / Deletion

> tentative date for the 1st draft?

I can give you the first draft early next week (26th March).

**Comment by verma-kunal** [comment]
Thanks for the info. Looking forward to the post and all the best

**Comment by adityasamant25** [comment]
Hi @verma-kunal,
As promised, I have raised the PR for the blog.
Kindly review it and I'm available for incorporating any changes that seem necessary.

Kind Regards,
Aditya.
